name: dev CI/CD

on:
  push:
    branches:
      - dev

env:
  env_var: ${{ secrets.ENV_CONTEXT_VAR }}

jobs:
  spring_boot_build:
    name: spring boot build
    uses: ./.github/workflows/spring_boot_build.yml

  deply_beanstalk:
    needs: spring_boot_build
    uses: ./.github/workflows/deploy_beanstalk.yml
    with:
      environment_name: ${{ secrets.EB_ENVIRONMENT_NAME }}
      application_name: ${{ secrets.EB_APPLICATION_NAME }}
      region: ${{ secrets.AWS_REGION }}
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
