# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# Repo Action 페이지에 나타날 이름
name: Spring Boot & Gradle CI

on:
  workflow_call:

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
      - name: Checkout commits
        uses: actions/checkout@v3

      - name: Set up JDK 1.11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: "adopt"

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle spotlessApply
        run: ./gradlew spotlessApply

      - name: Build with Gradle
        run: ./gradlew clean build
